### PR TITLE
Initial seed file

### PR DESCRIPTION
**Pull request by mniians**
Messed up the branch somehow, it has every commit for some reason...Maybe because I branched within vs code? Not sure, but could either of you guys review my seed file? thanks @campbellia @jeremypurser

### CODE REVIEW

**Comment by campbellia** [comment]
Looks good Myers! One thing I noticed: it looks like your IMDB ratings are going up to 5 stars but I think it's actually a 10 star rating system?

**Comment by jeremypurser** [comment]
@mniians Nice and clean! I like the way you have it broken down. I'm wondering for your `createMovie` function — is 4 images enough for `imageUrls`?

**Comment by mniians** [comment]
Thanks for the feedback! Making those changes now!

**Comment by mniians** [comment]
Hey guys, I've increased the ratings, I also included 25 images for the imageUrls!

**Pull request merged**
